# yaml-language-server: $schema=https://raw.githubusercontent.com/azure/azure-dev/main/schemas/v1.0/azure.yaml.json
name: jjflipbook-azure
infra:
  provider: bicep
  path: infra
services:
  backend:
    host: containerapp
    image: ${BACKEND_IMAGE}
  frontend:
    host: containerapp
    image: ${FRONTEND_IMAGE}
